---
title: "SCM Replications OECD Project"
output:
  html_document: default
  pdf_document: default
date: "2023-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Author: Patrick Klösel (patrick.kloesel@pik-potsdam.de), Laura Menicacci (laurame@pik-potsdam.de)

Date:   25/05/2023

Task:   Re-estimate breaks found in the OECD-project with SCM using the gsynth package
        (estimate SCM for each break in each sector in each country as a robustness check)


```{r libraries, echo = FALSE}
# Load Libraries
library(ggplot2)
library(tidyverse)
library(gsynth)
library(panelView)
library(patchwork)

# Load gsynth function with custom labels
source(".\\plot_cf_gsynth_custom.R")
```

```{r data, echo=FALSE}
# Load Data
data <- read_rds(".\\ghg_co2_manual_edgar_final_ets_dummies_updated_fixed.RDS")

# Define The Two Samples
AC1 <- c("Australia", "Austria", "Belgium", "Bulgaria", "Canada", "Croatia",        
         "Czech Republic" , "Denmark", "Estonia" ,"Finland","France", "Germany",        
         "Greece", "Hungary","Iceland","Ireland", "Italy","Japan" ,         
         "Latvia","Lithuania", "Luxembourg","Malta","Netherlands","New Zealand",
         "Norway","Poland","Portugal","Romania", "Slovak Republic", "Slovenia"  ,
         "Spain","Sweden","Switzerland","United Kingdom" , "United States")  
AC6 <- c("Argentina","Brazil","Chile","Colombia","China","Costa Rica","India",
         "Indonesia","Mexico","Peru","Russia","Saudi Arabia","South Africa",
         "South Korea","Turkey") 

# Restrict Time Series to 2000-2021 and to AC1
data %>% subset(country  %in%  AC1) %>% subset(year >= 2000) -> ac1
# Restrict Time Series to 2000-2021 and to AC6
data %>% subset(country  %in%  AC6) %>% subset(year >= 2000) -> ac6

# Sector Specific Controls
buildings_controls <- " ~ lgdp + lpop + lgdp_sq + hdd + cdd + Labels_Appliances_2001 + Labels_Appliances_2013 + MEPS_Appliances_2009 + MEPS_Appliances_2013"
electricity_controls <- " ~ lgdp + lpop + lgdp_sq + hdd + cdd + ETS_E_2005 + ETS_E_2018"
industry_controls <- " ~ lgdp + lpop + lgdp_sq + hdd + cdd + ETS_I_2005 + ETS_I_2018 + MEPS_ElectricMotors_2011 + MEPS_ElectricMotors_2015"
transport_controls <- " ~ lgdp + lpop + lgdp_sq + hdd + cdd + MEPS_T_2009" 

```

## Electricity Sector

## AC1

```{r elec-ac1-mod, cache=TRUE}
## AC1
data <- ac1

# Create Staggered SCM Treatments
data$treated <- 0
data$treated <- ifelse(data$country == "United Kingdom" & data$year >= 2015, 1, data$treated)
#data$treated <- ifelse(data$country == "United Kingdom" & data$year >= 2016, 1, data$treated)
data$treated <- ifelse(data$country == "Sweden" & data$year >= 2005, 1, data$treated)
data$treated <- ifelse(data$country == "Portugal" & data$year >= 2019, 1, data$treated)
data$treated <- ifelse(data$country == "Norway" & data$year >= 2012, 1, data$treated)
data$treated <- ifelse(data$country == "New Zealand" & data$year >= 2009, 1, data$treated)
#data$treated <- ifelse(data$country == "New Zealand" & data$year >= 2014, 1, data$treated)

# Check Treatments
v1 <- panelview(electricity_heat_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          cex.legend = 8, 
          background = "white", 
          xlab = "Year", 
          ylab = "Country") + ggtitle("Country Sample: Annex I") +
  theme(plot.title = element_text(size = 12))


# Run Gsynth with Staggered Treatments (IFE)
system.time(
  out <- gsynth(log_electricity_heat_co2 ~ treated 
                + hdd + cdd + lgdp + lpop + lgdp_sq
                + ETS_E_2005 + ETS_E_2018
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_electricity_ac1_output.RDS")
```

```{r,  figures-electricity-ac1, fig.show="hold", out.width="50%"}

plot(out, type = "gap", id = "United Kingdom", main = "United Kingdom 2015 (E)")

plot(out, type = "ct", id = "United Kingdom", main = "United Kingdom 2015 (E)") #+ geom_vline(aes(xintercept=2016), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2016

plot(out, type = "gap", id = "Sweden", main = "Sweden 2005 (E)")

plot(out, type = "ct", id = "Sweden", main = "Sweden 2005 (E)")


plot(out, type = "gap", id = "Portugal", main = "Portugal 2019 (E)")

plot(out, type = "ct", id = "Portugal", main = "Portugal 2019 (E)")


plot(out, type = "gap", id = "Norway", main = "Norway 2012 (E)")

plot(out, type = "ct", id = "Norway", main = "Norway 2012 (E)")


plot(out, type = "gap", id = "New Zealand", main = "New Zealand 2009 (E)")

plot(out, type = "ct", id = "New Zealand", main = "New Zealand 2009 (E)") #+ geom_vline(aes(xintercept=2014), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2014

```

## AC6

```{r elec-ac6-mod, cache=TRUE}
## AC6
data <- ac6

# Create Staggered SCM Treatments
data$treated <- 0
data$treated <- ifelse(data$country == "Brazil" & data$year >= 2016, 1, data$treated)
#data$treated <- ifelse(data$country == "Colombia" & data$year >= 2004, 1, data$treated)
data$treated <- ifelse(data$country == "Colombia" & data$year >= 2011, 1, data$treated)

# Check Treatments
v2 <- panelview(log_electricity_heat_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          cex.legend = 8, 
          background = "white", 
          xlab = "", 
          ylab = "") + ggtitle("Country Sample: Non-Annex I") +
  theme(plot.title = element_text(size = 12))

# Run Gsynth with Staggered Treatments (IFE)
system.time(
  out <- gsynth(log_electricity_heat_co2 ~ treated 
                + hdd + cdd + lgdp + lpop + lgdp_sq
                #+ ETS_E_2005 + ETS_E_2018 # Excluded because they do not apply
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_electricity_ac6_output.RDS")

```

```{r,  figures-electricity-ac6, fig.show="hold", out.width="50%"}

plot(out, type = "gap", id = "Brazil", main = "Brazil 2016 (E)")

plot(out, type = "ct", id = "Brazil", main = "Brazil 2016 (E)")

plot(out, type = "gap", id = "Colombia", main = "Colombia 2011 (E)")

plot(out, type = "ct", id = "Colombia", main = "Colombia 2011 (E)") #+ geom_vline(aes(xintercept=2004), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2004 

```

```{r combine-elec, echo=FALSE, include=FALSE}

treatment_status_elec <- v1 + v2 + plot_layout(guides = "collect", byrow = F, widths = c(12, 12)) + plot_annotation(title = 'Sector Electricity',
                  theme = theme(plot.title = element_text(size = 16), 
                                legend.position = "bottom", 
                                legend.text=element_text(size=12)))

#ggsave(".\\figures\\treatment_status_elec.jpg", plot = treatment_status_elec, device = "jpg", width = 10, height = 5)

```

## Industry Sector

## AC1


```{r industry-ac1-mod, cache=TRUE}
## AC1
data <- ac1

# Create Treatment Dummy for Treatment
data$treated <- 0
#data$treated <- ifelse(data$country == "Belgium" & data$year >= 2002, 1, 0)
data$treated <- ifelse(data$country == "Bulgaria" & data$year >= 2008, 1, data$treated)
#data$treated <- ifelse(data$country == "Bulgaria" & data$year >= 2009, 1, data$treated)
data$treated <- ifelse(data$country == "Canada" & data$year >= 2005, 1, data$treated)
data$treated <- ifelse(data$country == "Czech Republic" & data$year >= 2010, 1, data$treated)
data$treated <- ifelse(data$country == "France" & data$year >= 2017, 1, data$treated)
data$treated <- ifelse(data$country == "Ireland" & data$year >= 2009, 1, data$treated)
data$treated <- ifelse(data$country == "Italy" & data$year >= 2013, 1, data$treated)
#data$treated <- ifelse(data$country == "New Zealand" & data$year >= 2003, 1, data$treated)
#data$treated <- ifelse(data$country == "New Zealand" & data$year >= 2005, 1, data$treated)
data$treated <- ifelse(data$country == "Romania" & data$year >= 2009, 1, data$treated)

# Check Treatments
v1 <- panelview(log_industry_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          background = "white", 
          xlab = "Year", 
          ylab = "Country") + ggtitle("Country Sample: Annex I") +
  theme(plot.title = element_text(size = 12)) 

# Run Gsynth with Staggered Treatments (IFE)
system.time(
  out <- gsynth(log_industry_co2 ~ treated +
                  lgdp + lpop + lgdp_sq + hdd + cdd + 
                  ETS_I_2005 + ETS_I_2018 + 
                  MEPS_ElectricMotors_2011 + MEPS_ElectricMotors_2015
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_industry_ac1_output.RDS")

```


```{r,  figures-industry-ac1, fig.show="hold", out.width="50%"}

# Plot Individual Treatment Effects (Difference Factual and Counterfactual)
plot(out, type = "gap", id = "Bulgaria", main = "Bulgaria 2008 (I)")
plot(out, type = "ct", id = "Bulgaria", main = "Bulgaria 2008 (I)") #+ geom_vline(aes(xintercept=2009), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2009


plot(out, type = "gap", id = "Canada", main = "Canada 2005 (I)")
plot(out, type = "ct", id = "Canada", main = "Canada 2005 (I)")

plot(out, type = "gap", id = "Czech Republic", main = "Czech Republic 2010 (I)")
plot(out, type = "ct", id = "Czech Republic", main = "Czech Republic 2010 (I)")


plot(out, type = "gap", id = "France", main = "France 2017 (I)")
plot(out, type = "ct", id = "France", main = "France 2017 (I)")


plot(out, type = "gap", id = "Ireland", main = "Ireland 2009 (I)")
plot(out, type = "ct", id = "Ireland", main = "Ireland 2009 (I)")


plot(out, type = "gap", id = "Italy", main = "Italy 2013 (I)")
plot(out, type = "ct", id = "Italy", main = "Italy 2013 (I)")


#plot(out, type = "gap", id = "New Zealand", main = "New Zealand 2005 (I)")
#plot(out, type = "ct", id = "New Zealand", main = "New Zealand 2005 (I)")


plot(out, type = "gap", id = "Romania", main = "Romania 2009 (I)")
plot(out, type = "ct", id = "Romania", main = "Romania 2009 (I)")
```
## AC6

```{r industry-ac6-mod, cache=TRUE}
# AC6
data <- ac6

# Treatments
data$treated <- 0
data$treated <- ifelse(data$country == "China" & data$year >= 2016, 1, data$treated)
data$treated <- ifelse(data$country == "Indonesia" & data$year >= 2013, 1, data$treated)
#data$treated <- ifelse(data$country == "Russia" & data$year >= 2004, 1, data$treated)
data$treated <- ifelse(data$country == "Saudi Arabia" & data$year >= 2016, 1, data$treated)
#data$treated <- ifelse(data$country == "South Korea" & data$year >= 2004, 1, data$treated)

# Check Treatments
v2 <- panelview(log_industry_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          background = "white", 
          xlab = "", 
          ylab = "") + ggtitle("Country Sample: Non-Annex I") +
  theme(plot.title = element_text(size = 12)) 

system.time(
  out <- gsynth(log_industry_co2 ~ treated +
                  lgdp + lpop + lgdp_sq + hdd + cdd #+ 
                #  ETS_I_2005 + ETS_I_2018 + 
                #  MEPS_ElectricMotors_2011 + MEPS_ElectricMotors_2015
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 5), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_industry_ac6_output.RDS")

```


```{r,  figures-industry-ac6, fig.show="hold", out.width="50%"}
plot(out, type = "gap", id = "China", main = "China 2016 (I)")
plot(out, type = "ct", id = "China", main = "China 2016 (I)") #+ geom_vline(aes(xintercept=2018), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2018
#
plot(out, type = "gap", id = "Indonesia", main = "Indonesia 2013 (I)")
plot(out, type = "ct", id = "Indonesia", main = "Indonesia 2013 (I)")
#
plot(out, type = "gap", id = "Saudi Arabia", main = "Saudi Arabia 2016 (I)")
plot(out, type = "ct", id = "Saudi Arabia", main = "Saudi Arabia 2016 (I)")

```

```{r combine-industry, echo=FALSE, include=FALSE}

treatment_status_industry <- v1 + v2 + plot_layout(guides = "collect", byrow = F, widths = c(12, 12)) + plot_annotation(title = 'Sector Industry',
                  theme = theme(plot.title = element_text(size = 16), 
                                legend.position = "bottom", 
                                legend.text=element_text(size=12)))

#ggsave(".\\figures\\treatment_status_industry.jpg", plot = treatment_status_industry, device = "jpg", width = 10, height = 5)

```

## Transport Sector

## AC1

```{r transp-ac1-mod, cache=TRUE}
## AC1
data <- ac1

# Create Staggered SCM Treatments
data$treated <- 0
data$treated <- ifelse(data$country == "Austria" & data$year >= 2006, 1, data$treated)
data$treated <- ifelse(data$country == "Denmark" & data$year >= 2020, 1, data$treated)
#data$treated <- ifelse(data$country == "France" & data$year >= 2004, 1, data$treated)
#data$treated <- ifelse(data$country == "Germany" & data$year >= 2002, 1, data$treated)
data$treated <- ifelse(data$country == "Germany" & data$year >= 2005, 1, data$treated)
data$treated <- ifelse(data$country == "Hungary" & data$year >= 2011, 1, data$treated)
data$treated <- ifelse(data$country == "Ireland" & data$year >= 2015, 1, data$treated)
#data$treated <- ifelse(data$country == "Ireland" & data$year >= 2020, 1, data$treated)
data$treated <- ifelse(data$country == "Norway" & data$year >= 2016, 1, data$treated)
data$treated <- ifelse(data$country == "Poland" & data$year >= 2013, 1, data$treated)
data$treated <- ifelse(data$country == "Romania" & data$year >= 2005, 1, data$treated)
#data$treated <- ifelse(data$country == "Slovak Republic" & data$year >= 2003, 1, data$treated)
data$treated <- ifelse(data$country == "Spain" & data$year >= 2009, 1, data$treated)
data$treated <- ifelse(data$country == "Sweden" & data$year >= 2016, 1, data$treated)
data$treated <- ifelse(data$country == "United States" & data$year >= 2008, 1, data$treated)

# Check Treatments
v1 <- panelview(log_transport_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          background = "white", 
          xlab = "Year", 
          ylab = "Country") + ggtitle("Country Sample: Annex I") +
  theme(plot.title = element_text(size = 12)) 

# Run Gsynth with Staggered Treatments (IFE)
system.time(
  out <- gsynth(log_transport_co2 ~ treated 
                + hdd + cdd + lgdp + lpop + lgdp_sq
                + MEPS_T_2009
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_transport_ac1_output.RDS")

```


```{r,  figures-transport-ac1, fig.show="hold", out.width="50%"}
# Plot Individual Treatment Effects (Difference Factual and Counterfactual)
plot(out, type = "gap", id = "Austria", main = "Austria 2006 (T)")
plot(out, type = "ct", id = "Austria", main = "Austria 2006 (T)")
#
plot(out, type = "gap", id = "Denmark", main = "Denmark 2020 (T)")
plot(out, type = "ct", id = "Denmark", main = "Denmark 2020 (T)")

plot(out, type = "gap", id = "Germany", main = "Germany 2005 (T)")
plot(out, type = "ct", id = "Germany", main = "Germany 2005 (T)") + geom_vline(aes(xintercept=2002), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2002

#
plot(out, type = "gap", id = "Hungary", main = "Hungary 2011 (T)")
plot(out, type = "ct", id = "Hungary", main = "Hungary 2011 (T)")

plot(out, type = "gap", id = "Ireland", main = "Ireland 2015 (T)")
plot(out, type = "ct", id = "Ireland", main = "Ireland 2015 (T)") + geom_vline(aes(xintercept=2020), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2020

plot(out, type = "gap", id = "Norway", main = "Norway 2016 (T)")
plot(out, type = "ct", id = "Norway", main = "Norway 2016 (T)")

plot(out, type = "gap", id = "Poland", main = "Poland 2013 (T)")
plot(out, type = "ct", id = "Poland", main = "Poland 2013 (T)")

plot(out, type = "gap", id = "Romania", main = "Romania 2005 (T)")
plot(out, type = "ct", id = "Romania", main = "Romania 2005 (T)")
#
plot(out, type = "gap", id = "Spain", main = "Spain 2009 (T)")
plot(out, type = "ct", id = "Spain", main = "Spain 2009 (T)")
#
plot(out, type = "gap", id = "Sweden", main = "Sweden 2016 (T)")
plot(out, type = "ct", id = "Sweden", main = "Sweden 2016 (T)")
#
plot(out, type = "gap", id = "United States", main = "United States 2008 (T)")
plot(out, type = "ct", id = "United States", main = "United States 2008 (T)")
```

## AC6 

```{r transp-ac6-mod, cache=TRUE}
# AC6
data <- ac6

# Treatments
data$treated <- 0
#data$treated <- ifelse(data$country == "Colombia" & data$year >= 2002, 1, data$treated)
data$treated <- ifelse(data$country == "Colombia" & data$year >= 2008, 1, data$treated)
data$treated <- ifelse(data$country == "Mexico" & data$year >= 2020, 1, data$treated)
data$treated <- ifelse(data$country == "South Korea" & data$year >= 2008, 1, data$treated)

# Check Treatments
v2 <- panelview(log_transport_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          background = "white", 
          xlab = "", 
          ylab = "") + ggtitle("Country Sample: Non-Annex I") +
  theme(plot.title = element_text(size = 12)) 

system.time(
  out <- gsynth(log_transport_co2 ~ treated 
                + hdd + cdd + lgdp + lpop + lgdp_sq
#                + MEPS_T_2009
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_transport_ac6_output.RDS")

```


```{r,  figures-transport-ac6, fig.show="hold", out.width="50%"}
# Plot Individual Treatment Effects (Difference Factual and Counterfactual)
plot(out, type = "gap", id = "Colombia", main = "Colombia 2008 (T)")
plot(out, type = "ct", id = "Colombia", main = "Colombia 2008 (T)") #+ geom_vline(aes(xintercept=2002), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2002

plot(out, type = "gap", id = "Mexico", main = "Mexico 2020 (T)")
plot(out, type = "ct", id = "Mexico", main = "Mexico 2020 (T)")

plot(out, type = "gap", id = "South Korea", main = "South Korea 2008 (T)")
plot(out, type = "ct", id = "South Korea", main = "South Korea 2008 (T)")

```

```{r combine-transport, echo=FALSE, include=FALSE}

treatment_status_transport <- v1 + v2 + plot_layout(guides = "collect", byrow = F, widths = c(12, 12)) + plot_annotation(title = 'Sector Transport',
                  theme = theme(plot.title = element_text(size = 16), 
                                legend.position = "bottom", 
                                legend.text=element_text(size=12)))

#ggsave(".\\figures\\treatment_status_transport.jpg", plot = treatment_status_transport, device = "jpg", width = 10, height = 5)

```

## Buildings Sector

## AC1

```{r build-ac1-mod, cache=TRUE}
## AC1
data <- ac1

# Create Staggered SCM Treatments
data$treated <- 0
data$treated <- ifelse(data$country == "Australia" & data$year >= 2019, 1, data$treated)
data$treated <- ifelse(data$country == "Czech Republic" & data$year >= 2005, 1, data$treated)
data$treated <- ifelse(data$country == "Denmark" & data$year >= 2020, 1, data$treated)
data$treated <- ifelse(data$country == "Greece" & data$year >= 2012, 1, data$treated)
#data$treated <- ifelse(data$country == "Greece" & data$year >= 2013, 1, data$treated)
data$treated <- ifelse(data$country == "Ireland" & data$year >= 2015, 1, data$treated)
#data$treated <- ifelse(data$country == "Ireland" & data$year >= 2020, 1, data$treated)
data$treated <- ifelse(data$country == "New Zealand" & data$year >= 2018, 1, data$treated)
data$treated <- ifelse(data$country == "Norway" & data$year >= 2015, 1, data$treated)
data$treated <- ifelse(data$country == "Poland" & data$year >= 2019, 1, data$treated)
#data$treated <- ifelse(data$country == "Slovak Republic" & data$year >= 2001, 1, data$treated)
#data$treated <- ifelse(data$country == "Slovak Republic" & data$year >= 2003, 1, data$treated)
data$treated <- ifelse(data$country == "Slovak Republic" & data$year >= 2011, 1, data$treated)
#data$treated <- ifelse(data$country == "Slovak Republic" & data$year >= 2015, 1, data$treated)
#data$treated <- ifelse(data$country == "Sweden" & data$year >= 2004, 1, data$treated)

# Check Treatments
v1 <- panelview(log_buildings_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          background = "white", 
          xlab = "Year", 
          ylab = "Country") + ggtitle("Country Sample: Annex I") +
  theme(plot.title = element_text(size = 12)) 

# Run Gsynth with Staggered Treatments (IFE)
system.time(
  out <- gsynth(log_transport_co2 ~ treated 
                + hdd + cdd + lgdp + lpop + lgdp_sq
                + Labels_Appliances_2001 + Labels_Appliances_2013 + MEPS_Appliances_2009 #+ MEPS_Appliances_2013
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_buildings_ac1_output.RDS")

```


```{r,  figures-buildings-ac1, fig.show="hold", out.width="50%"}
# Plot Individual Treatment Effects (Difference Factual and Counterfactual)
plot(out, type = "gap", id = "Australia", main = "Australia 2019 (B)")
plot(out, type = "ct", id = "Australia", main = "Australia 2019 (B)")
#
plot(out, type = "gap", id = "Czech Republic", main = "Czech Republic 2005 (B)")
plot(out, type = "ct", id = "Czech Republic", main = "Czech Republic 2005 (B)")
#
plot(out, type = "gap", id = "Denmark", main = "Denmark 2020 (B)")
plot(out, type = "ct", id = "Denmark", main = "Denmark 2020 (B)")

plot(out, type = "gap", id = "Greece", main = "Greece 2012 (B)")
plot(out, type = "ct", id = "Greece", main = "Greece 2012 (B)") #+ geom_vline(aes(xintercept=2013), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2013

plot(out, type = "gap", id = "Ireland", main = "Ireland 2015 (B)")
plot(out, type = "ct", id = "Ireland", main = "Ireland 2015 (B)") #+ geom_vline(aes(xintercept=2020), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2020

plot(out, type = "gap", id = "New Zealand", main = "New Zealand 2018 (B)")
plot(out, type = "ct", id = "New Zealand", main = "New Zealand 2018 (B)")

plot(out, type = "gap", id = "Norway", main = "Norway 2015 (B)")
plot(out, type = "ct", id = "Norway", main = "Norway 2015 (B)")
#
plot(out, type = "gap", id = "Poland", main = "Poland 2019 (B)")
plot(out, type = "ct", id = "Poland", main = "Poland 2019 (B)")
#
plot(out, type = "gap", id = "Slovak Republic", main = "Slovak Republic 2011 (B)")
plot(out, type = "ct", id = "Slovak Republic", main = "Slovak Republic 2011 (B)")  #+ geom_vline(aes(xintercept=2001), colour = "#AAAAAA70", size = 2, linetype = "solid") + geom_vline(aes(xintercept=2003), colour = "#AAAAAA70", size = 2, linetype = "solid") + geom_vline(aes(xintercept=2015), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2001 - 2003 - 2015

```

## AC6

```{r build-ac6-mod, cache=TRUE}
# AC6
data <- ac6

# Treatments
data$treated <- 0
data$treated <- ifelse(data$country == "Argentina" & data$year >= 2017, 1, data$treated)
data$treated <- ifelse(data$country == "China" & data$year >= 2018, 1, data$treated)
data$treated <- ifelse(data$country == "Colombia" & data$year >= 2013, 1, data$treated)
#data$treated <- ifelse(data$country == "Peru" & data$year >= 2003, 1, data$treated)
data$treated <- ifelse(data$country == "Peru" & data$year >= 2006, 1, data$treated)
data$treated <- ifelse(data$country == "South Africa" & data$year >= 2010, 1, data$treated)
#data$treated <- ifelse(data$country == "South Africa" & data$year >= 2015, 1, data$treated)
#data$treated <- ifelse(data$country == "South Africa" & data$year >= 2020, 1, data$treated)
data$treated <- ifelse(data$country == "Turkey" & data$year >= 2013, 1, data$treated)


# Check Treatments
v2 <- panelview(log_buildings_co2 ~ treated, data = data,  
          index = c("country","year"), 
          pre.post = TRUE,
          axis.adjust = TRUE,
          cex.axis.y = 4, 
          background = "white", 
          xlab = "", 
          ylab = "") + ggtitle("Country Sample: Non-Annex I") +
  theme(plot.title = element_text(size = 12)) 

# Run Gsynth with Staggered Treatments (IFE)
system.time(
  out <- gsynth(log_transport_co2 ~ treated 
                + hdd + cdd + lgdp + lpop + lgdp_sq
                ,
                data = data, 
                index = c("country","year"), force = "two-way", 
                CV = TRUE, r = c(0, 3), se = TRUE, 
                inference = "parametric", nboots = 1000, 
                parallel = FALSE, estimator = "ife")
)

#saveRDS(out, file = ".\\gsynth_buildings_ac6_output.RDS")

```


```{r,  figures-buildings-ac6, fig.show="hold", out.width="50%"}
# Plot Individual Treatment Effects (Difference Factual and Counterfactual)
plot(out, type = "gap", id = "Argentina", main = "Argentina 2017 (B)")
plot(out, type = "ct", id = "Argentina", main = "Argentina 2017 (B)")
#
plot(out, type = "gap", id = "China", main = "China 2018 (B)")
plot(out, type = "ct", id = "China", main = "China 2018 (B)")
#
plot(out, type = "gap", id = "Colombia", main = "Colombia 2013 (B)")
plot(out, type = "ct", id = "Colombia", main = "Colombia 2013 (B)")

plot(out, type = "gap", id = "Peru", main = "Peru 2006 (B)")
plot(out, type = "ct", id = "Peru", main = "Peru 2006 (B)") + geom_vline(aes(xintercept=2003), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2003

plot(out, type = "gap", id = "South Africa", main = "South Africa 2010 (B)")
plot(out, type = "ct", id = "South Africa", main = "South Africa 2010 (B)") + geom_vline(aes(xintercept=2015), colour = "#AAAAAA70", size = 2, linetype = "solid") + geom_vline(aes(xintercept=2020), colour = "#AAAAAA70", size = 2, linetype = "solid") # add second break: 2015 - 2020

plot(out, type = "gap", id = "Turkey", main = "Turkey 2013 (B)")
plot(out, type = "ct", id = "Turkey", main = "Turkey 2013 (B)")

```


```{r combine-buildings, echo=FALSE, include=FALSE}

treatment_status_buildings <- v1 + v2 + plot_layout(guides = "collect", byrow = F, widths = c(12, 12)) + plot_annotation(title = 'Sector Buildings',
                  theme = theme(plot.title = element_text(size = 16), 
                                legend.position = "bottom", 
                                legend.text=element_text(size=12)))

#ggsave(".\\figures\\treatment_status_buildings.jpg", plot = treatment_status_buildings, device = "jpg", width = 10, height = 5)

```



